baseURL = "https://ashishsaxena.net"
languageCode = "en-us"
title = "Ashish Saxena's Personal Website"
theme = "reak-blog"
enableRobotsTXT = "true"

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
post = "/:year/:month/:slug/"
year = "/:slug/"
month = "/:slug/"
tags = "/tag/:slug"
categories = "/category/:slug"

[params]
blogName = "Ashish Saxena"
blogSubtitle = "My personal website and random ramblings"
avatarURL = "images/profile.png"
paginationLimit = "10"
maxPostsHomePage = "100"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    pre = "contact"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "Archive"
    pre = "archive"
    url = "/archive/"
    weight = 4
  [[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ashishsaxena5/"
  [[menu.social]]
    name = "github"
    url = "https://github.com/eclipsed-ninja/"
  [[menu.social]]
    name = "twitter"
    url = "https://twitter.com/eclipsed_ninja"
  [[menu.social]]
    name = "facebook"
    url = "https://www.facebook.com/saxena.ashish55/"
