baseURL = "https://ashishsaxena.net"
languageCode = "en-us"
title = "Ashish Saxena - My personal thoughts, ideas and rants"
theme = "reak-blog"
enableRobotsTXT = "true"
googleAnalytics = "UA-180784437-1"

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"
series = "series"

[permalinks]
post = "/:year/:month/:slug/"
year = "/:slug/"
month = "/:slug/"
tags = "/tag/:slug"
categories = "/category/:slug"

[params]
title = "Ashish Saxena"
seodescription = "It's my personal website, which I use as a public journal on the internet to jot down my personal ideas, findings and rants. I'm Ashish Saxena, founder of REAK INFOTECH LLP."
description = "My personal thoughts, ideas and rants"
images = ["images/profile.png"]
paginationLimit = "10"
maxPostsHomePage = "100"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    pre = "contact"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "Archive"
    pre = "archive"
    url = "/archive/"
    weight = 4
  [[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ashishsaxena5/"
  [[menu.social]]
    name = "github"
    url = "https://github.com/eclipsed-ninja/"
  [[menu.social]]
    name = "twitter"
    url = "https://twitter.com/eclipsed_ninja"
  [[menu.social]]
    name = "facebook"
    url = "https://www.facebook.com/saxena.ashish55/"
