baseURL = "https://reak-infotech-llp.github.io/hugo-personal-blog/"
languageCode = "en-us"
title = "Personal Blog"
theme = "reak-blog"

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
post = "/:year/:month/:slug/"
year = "/:slug/"
month = "/:slug/"
tags = "/tag/:slug"
categories = "/category/:slug"

[params]
blogName = "John Doe"
blogDescription = "Personal Blog of John Doe"
avatarURL = "https://bulma.io/images/placeholders/128x128.png"
postsOnHome = 10

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    pre = "contact"
    url = "/contact/"
    weight = 3
